# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import variable
import os

curdir = os.path.dirname(__file__)

class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(981, 580)
        Dialog.setStyleSheet("")
        self.Button_main = QtWidgets.QPushButton(Dialog)
        self.Button_main.setGeometry(QtCore.QRect(20, 190, 171, 31))
        self.Button_main.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    \n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(218, 218, 218);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/house2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_main.setIcon(icon)
        self.Button_main.setObjectName("Button_main")
        self.Button_settings = QtWidgets.QPushButton(Dialog)
        self.Button_settings.setGeometry(QtCore.QRect(20, 240, 171, 31))
        self.Button_settings.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    color:  rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/settings2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_settings.setIcon(icon1)
        self.Button_settings.setObjectName("Button_settings")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 0, 771, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(440, 530, 301, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_18 = QtWidgets.QPushButton(self.page)
        self.pushButton_18.setGeometry(QtCore.QRect(290, 240, 161, 51))
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    \n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(218, 218, 218);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Button_page1_main = QtWidgets.QPushButton(self.page_2)
        self.Button_page1_main.setGeometry(QtCore.QRect(110, 22, 121, 31))
        self.Button_page1_main.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/основное2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_page1_main.setIcon(icon2)
        self.Button_page1_main.setObjectName("Button_page1_main")
        self.Button_page2_programms = QtWidgets.QPushButton(self.page_2)
        self.Button_page2_programms.setGeometry(QtCore.QRect(324, 20, 121, 31))
        self.Button_page2_programms.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/программы.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_page2_programms.setIcon(icon3)
        self.Button_page2_programms.setObjectName("Button_page2_programms")
        self.Button_page3_web = QtWidgets.QPushButton(self.page_2)
        self.Button_page3_web.setGeometry(QtCore.QRect(524, 22, 121, 31))
        self.Button_page3_web.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/сайты.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_page3_web.setIcon(icon4)
        self.Button_page3_web.setObjectName("Button_page3_web")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(-20, 65, 771, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 80, 761, 481))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_perekl3 = QtWidgets.QWidget()
        self.page_perekl3.setObjectName("page_perekl3")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_perekl3)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 0, 91, 23))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_perekl3)
        self.pushButton_12.setGeometry(QtCore.QRect(444, 0, 91, 23))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_perekl3)
        self.pushButton_13.setGeometry(QtCore.QRect(234, 0, 91, 23))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_perekl3)
        self.pushButton_14.setGeometry(QtCore.QRect(634, 0, 91, 23))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.page_perekl3)
        self.stackedWidget_4.setGeometry(QtCore.QRect(10, 30, 751, 461))
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_10.setGeometry(QtCore.QRect(310, 270, 121, 31))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/free-icon-done-4123617.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(260, 100, 241, 20))
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_10.setInputMask("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(260, 190, 241, 20))
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_20 = QtWidgets.QLabel(self.page_7)
        self.label_20.setGeometry(QtCore.QRect(300, 140, 221, 41))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setGeometry(QtCore.QRect(350, 10, 131, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_7)
        self.label_22.setGeometry(QtCore.QRect(250, 50, 321, 21))
        self.label_22.setObjectName("label_22")
        self.label_33 = QtWidgets.QLabel(self.page_7)
        self.label_33.setGeometry(QtCore.QRect(280, 220, 211, 16))
        self.label_33.setObjectName("label_33")
        self.stackedWidget_4.addWidget(self.page_7)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_12.setGeometry(QtCore.QRect(260, 100, 241, 20))
        self.lineEdit_12.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_12.setInputMask("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_15.setGeometry(QtCore.QRect(310, 270, 121, 31))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_15.setIcon(icon5)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_23 = QtWidgets.QLabel(self.page_9)
        self.label_23.setGeometry(QtCore.QRect(300, 140, 221, 41))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_9)
        self.label_24.setGeometry(QtCore.QRect(350, 10, 131, 31))
        self.label_24.setObjectName("label_24")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_13.setGeometry(QtCore.QRect(260, 190, 241, 20))
        self.lineEdit_13.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_25 = QtWidgets.QLabel(self.page_9)
        self.label_25.setGeometry(QtCore.QRect(250, 50, 321, 21))
        self.label_25.setObjectName("label_25")
        self.stackedWidget_4.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_10)
        self.lineEdit_14.setGeometry(QtCore.QRect(260, 100, 241, 20))
        self.lineEdit_14.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_14.setInputMask("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_16.setGeometry(QtCore.QRect(310, 270, 121, 31))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_16.setIcon(icon5)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_26 = QtWidgets.QLabel(self.page_10)
        self.label_26.setGeometry(QtCore.QRect(300, 140, 221, 41))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.page_10)
        self.label_27.setGeometry(QtCore.QRect(350, 10, 131, 31))
        self.label_27.setObjectName("label_27")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.page_10)
        self.lineEdit_15.setGeometry(QtCore.QRect(260, 190, 241, 20))
        self.lineEdit_15.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_28 = QtWidgets.QLabel(self.page_10)
        self.label_28.setGeometry(QtCore.QRect(250, 50, 321, 21))
        self.label_28.setObjectName("label_28")
        self.stackedWidget_4.addWidget(self.page_10)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_16.setGeometry(QtCore.QRect(260, 100, 241, 20))
        self.lineEdit_16.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_16.setInputMask("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_17.setGeometry(QtCore.QRect(310, 270, 121, 31))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_17.setIcon(icon5)
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_29 = QtWidgets.QLabel(self.page_8)
        self.label_29.setGeometry(QtCore.QRect(300, 140, 221, 41))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.page_8)
        self.label_30.setGeometry(QtCore.QRect(350, 10, 131, 31))
        self.label_30.setObjectName("label_30")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_17.setGeometry(QtCore.QRect(260, 190, 241, 20))
        self.lineEdit_17.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_31 = QtWidgets.QLabel(self.page_8)
        self.label_31.setGeometry(QtCore.QRect(250, 50, 321, 21))
        self.label_31.setObjectName("label_31")
        self.stackedWidget_4.addWidget(self.page_8)
        self.stackedWidget_2.addWidget(self.page_perekl3)
        self.page_perekl1 = QtWidgets.QWidget()
        self.page_perekl1.setObjectName("page_perekl1")
        self.label_4 = QtWidgets.QLabel(self.page_perekl1)
        self.label_4.setGeometry(QtCore.QRect(300, 30, 161, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.page_perekl1)
        self.lineEdit.setGeometry(QtCore.QRect(520, 70, 241, 20))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.page_perekl1)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 161, 51))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.page_perekl1)
        self.pushButton.setGeometry(QtCore.QRect(60, 70, 121, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_34 = QtWidgets.QLabel(self.page_perekl1)
        self.label_34.setGeometry(QtCore.QRect(190, 240, 271, 21))
        self.label_34.setObjectName("label_34")
        self.comboBox = QtWidgets.QComboBox(self.page_perekl1)
        self.comboBox.setGeometry(QtCore.QRect(470, 240, 131, 31))
        self.comboBox.setStyleSheet("\n"
"background-color: rgb(193, 193, 193);")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_perekl1)
        self.pushButton_19.setGeometry(QtCore.QRect(274, 70, 91, 31))
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.page_perekl1)
        self.pushButton_20.setGeometry(QtCore.QRect(380, 70, 91, 31))
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_35 = QtWidgets.QLabel(self.page_perekl1)
        self.label_35.setGeometry(QtCore.QRect(550, 40, 181, 31))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_perekl1)
        self.label_36.setGeometry(QtCore.QRect(570, 90, 141, 16))
        self.label_36.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_36.setObjectName("label_36")
        self.pushButton_21 = QtWidgets.QPushButton(self.page_perekl1)
        self.pushButton_21.setGeometry(QtCore.QRect(590, 110, 101, 23))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.stackedWidget_2.addWidget(self.page_perekl1)
        self.page_perekl2 = QtWidgets.QWidget()
        self.page_perekl2.setObjectName("page_perekl2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_perekl2)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 0, 91, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_perekl2)
        self.pushButton_3.setGeometry(QtCore.QRect(234, 0, 91, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_perekl2)
        self.pushButton_4.setGeometry(QtCore.QRect(444, 0, 91, 23))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_perekl2)
        self.pushButton_5.setGeometry(QtCore.QRect(634, 0, 91, 23))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_perekl2)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 30, 761, 461))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_7.setGeometry(QtCore.QRect(320, 270, 121, 31))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 100, 241, 20))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(270, 190, 241, 20))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(280, 140, 221, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(330, 10, 131, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(240, 50, 321, 21))
        self.label_13.setObjectName("label_13")
        self.stackedWidget_3.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_8.setGeometry(QtCore.QRect(320, 270, 121, 31))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 100, 241, 20))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(270, 190, 241, 20))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(self.page_5)
        self.label_14.setGeometry(QtCore.QRect(280, 140, 221, 41))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(330, 10, 131, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        self.label_16.setGeometry(QtCore.QRect(240, 50, 321, 21))
        self.label_16.setObjectName("label_16")
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 270, 121, 31))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 100, 241, 20))
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(270, 190, 241, 20))
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(280, 140, 221, 41))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setGeometry(QtCore.QRect(330, 10, 131, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(240, 50, 321, 21))
        self.label_19.setObjectName("label_19")
        self.stackedWidget_3.addWidget(self.page_6)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setGeometry(QtCore.QRect(330, 10, 131, 31))
        self.label_6.setObjectName("label_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_6.setGeometry(QtCore.QRect(320, 270, 121, 31))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    \n"
"    color: rgb(171, 171, 171);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(154, 154, 154);\n"
"}")
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 100, 241, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setGeometry(QtCore.QRect(240, 50, 321, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(280, 140, 221, 41))
        self.label_10.setObjectName("label_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 190, 241, 20))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"     \n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius:  10px;\n"
"    \n"
"    padding-left:    20px;\n"
"    padding-right:    20px;\n"
"    \n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setGeometry(QtCore.QRect(290, 220, 211, 16))
        self.label_32.setObjectName("label_32")
        self.stackedWidget_3.addWidget(self.page_4)
        self.stackedWidget_2.addWidget(self.page_perekl2)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 771, 71))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/wp2.png")))
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.Button_page1_main.raise_()
        self.Button_page2_programms.raise_()
        self.Button_page3_web.raise_()
        self.line_2.raise_()
        self.stackedWidget_2.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 0, 151, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/image_sokrat.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(200, 0, 21, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 140, 91, 21))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(0, 2, 211, 581))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(os.path.join(curdir, "иконки/font2.png")))
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.Button_main.raise_()
        self.Button_settings.raise_()
        self.stackedWidget.raise_()
        self.label_3.raise_()
        self.line.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget_4.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button_main.setText(_translate("Dialog", "Главная"))
        self.Button_settings.setText(_translate("Dialog", "Настройки"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#7a7a7a;\">Авторы: Хон Марк, Гриценко Дмитрий</span></p></body></html>"))
        self.pushButton_18.setText(_translate("Dialog", "Начать игру"))
        self.Button_page1_main.setText(_translate("Dialog", "Основное"))
        self.Button_page2_programms.setText(_translate("Dialog", "Программы"))
        self.Button_page3_web.setText(_translate("Dialog", "Сайты"))
        self.pushButton_11.setText(_translate("Dialog", "сайт 1"))
        self.pushButton_12.setText(_translate("Dialog", "сайт 3"))
        self.pushButton_13.setText(_translate("Dialog", "сайт 2"))
        self.pushButton_14.setText(_translate("Dialog", "сайт 4"))
        self.pushButton_10.setText(_translate("Dialog", "Готово"))
        self.lineEdit_10.setPlaceholderText(_translate("Dialog", "Введите Ссылку"))
        self.lineEdit_11.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия сайта</span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сайт 1</span></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ссылка для открытие сайта</span></p></body></html>"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#f10000;\">При разделение названий используйте ;</span></p></body></html>"))
        self.lineEdit_12.setPlaceholderText(_translate("Dialog", "Введите Ссылку"))
        self.pushButton_15.setText(_translate("Dialog", "Готово"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия сайта</span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сайт 2</span></p></body></html>"))
        self.lineEdit_13.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ссылка для открытие сайта</span></p></body></html>"))
        self.lineEdit_14.setPlaceholderText(_translate("Dialog", "Введите Ссылку"))
        self.pushButton_16.setText(_translate("Dialog", "Готово"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия сайта</span></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сайт 3</span></p></body></html>"))
        self.lineEdit_15.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ссылка для открытие сайта</span></p></body></html>"))
        self.lineEdit_16.setPlaceholderText(_translate("Dialog", "Введите Ссылку"))
        self.pushButton_17.setText(_translate("Dialog", "Готово"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия сайта</span></p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сайт 4</span></p></body></html>"))
        self.lineEdit_17.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ссылка для открытие сайта</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ответная фраза</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Введите число"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Сброс Настроек</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Сброс"))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Переключение микрофона</span></p></body></html>"))
        self.pushButton_19.setText(_translate("Dialog", "включить"))
        self.pushButton_20.setText(_translate("Dialog", "выключить"))
        self.label_35.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Время прослушки</span></p></body></html>"))
        self.label_36.setText(_translate("Dialog", "Запишите число больше 0"))
        self.pushButton_21.setText(_translate("Dialog", "сохранить"))
        self.pushButton_2.setText(_translate("Dialog", "Программа 1"))
        self.pushButton_3.setText(_translate("Dialog", "Программа 2"))
        self.pushButton_4.setText(_translate("Dialog", "Программа 3"))
        self.pushButton_5.setText(_translate("Dialog", "Программа 4"))
        self.pushButton_7.setText(_translate("Dialog", "Готово"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Введите Путь"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия программы</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Программа 2</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Путь для открытие программы</span></p></body></html>"))
        self.pushButton_8.setText(_translate("Dialog", "Готово"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "Введите Путь"))
        self.lineEdit_7.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия программы</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Программа 3</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Путь для открытие программы</span></p></body></html>"))
        self.pushButton_9.setText(_translate("Dialog", "Готово"))
        self.lineEdit_8.setPlaceholderText(_translate("Dialog", "Введите Путь"))
        self.lineEdit_9.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия программы</span></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Программа 4</span></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Путь для открытие программы</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Программа 1</span></p></body></html>"))
        self.pushButton_6.setText(_translate("Dialog", "Готово"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Введите Путь"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Путь для открытие программы</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Названия программы</span></p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Введите Название"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#f10000;\">При разделение названий используйте ;</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#3a3a3a;\">СОКРАТ</span></p></body></html>"))
